// <auto-generated />
using System;
using Aplikasi_Kota.Data_Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplikasi_Kota.Migrations
{
    [DbContext(typeof(KotaDbContext))]
    partial class KotaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aplikasi_Kota.Data_Model.MasterKecamatan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdKota")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KodeKecamatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamaKecamatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKota");

                    b.ToTable("Master_Kecamatan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdKota = 1,
                            IsDeleted = false,
                            KodeKecamatan = "DPK",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(3102),
                            NamaKecamatan = "Beji"
                        },
                        new
                        {
                            Id = 2,
                            IdKota = 1,
                            IsDeleted = false,
                            KodeKecamatan = "BJS",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(3104),
                            NamaKecamatan = "Bojongsari"
                        },
                        new
                        {
                            Id = 3,
                            IdKota = 1,
                            IsDeleted = false,
                            KodeKecamatan = "CLD",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(3106),
                            NamaKecamatan = "Cilodong"
                        },
                        new
                        {
                            Id = 4,
                            IdKota = 1,
                            IsDeleted = false,
                            KodeKecamatan = "BJT",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(3107),
                            NamaKecamatan = "Beji timur"
                        });
                });

            modelBuilder.Entity("Aplikasi_Kota.Data_Model.MasterKota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KodeKota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamaKota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Master_Kota", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            KodeKota = "DPK",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(2580),
                            NamaKota = "Depok"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            KodeKota = "DPK",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(2595),
                            NamaKota = "Jakarta Utara"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            KodeKota = "DPK",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(2597),
                            NamaKota = "Jakarta Selatan"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            KodeKota = "DPK",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 6, 24, 12, 33, 14, 281, DateTimeKind.Local).AddTicks(2598),
                            NamaKota = "Jakarta Barat"
                        });
                });

            modelBuilder.Entity("Aplikasi_Kota.Data_Model.MasterKecamatan", b =>
                {
                    b.HasOne("Aplikasi_Kota.Data_Model.MasterKota", "Kota")
                        .WithMany()
                        .HasForeignKey("IdKota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kota");
                });
#pragma warning restore 612, 618
        }
    }
}
